apiVersion: v1
kind: Service
metadata:
  name: django-app-service
  namespace: webapp
spec:
  selector:
    app: django-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30015
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-pod
  namespace: webapp
spec:
  selector:
    app: mongodb # select pods based on label
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP # create an internal IP address
