apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: webapp
  labels:
    type: local
spec:
  storageClassName: fast
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-pod
  namespace: webapp
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: mongodbadmin
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: secret
        volumeMounts:
          - name: mongodb-pvc
            mountPath: "/data/db"
  volumeClaimTemplates:
    - metadata:
        name: mongodb-pvc
        namespace: webapp
      spec:
        storageClassName: "fast"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
